### PR TITLE
adding vertical scrolling based on fixed visual textInput compared to hiddenInput

### PR DESCRIPTION
**Pull request by hanbollar**
## Linking

related to #590 

## Problem

*Description of the problem including potential code and/or screenshots as an example*

## Solution

*Quick explanation of change to be done*

### Breaking Change

*If this is a breaking change describe the before and after and why the change was necessary*

## Notes

*Notes and any associated research or links*

------------

## Required to Merge

- [x] **PASS** - all necessary actions must pass (excluding the auto-skipped ones)
- [x] **TEST IN HEADSET** - [main dev-testing-example](https://github.com/Volumetrics-io/mrjs/tree/main/samples/index.html) and any of the other [examples](https://github.com/Volumetrics-io/mrjs/tree/main/samples/examples) still work as expected
- [x] **VIDEO** - if this pr changes something visually - post a video here of it in headset-MR and/or on desktop (depending on what it affects) for the reviewer to reference.

https://github.com/Volumetrics-io/mrjs/assets/19377312/e76e3c27-4b07-45af-8e14-a9ba1060e3f9

- [x] **TITLE** - make sure the pr's title is updated appropriately as it will be used to name the commit on merge
~~- [ ] **BREAKING CHANGE**~~
  - **DOCUMENTATION**: This includes any changes to html tags and their components
    - make a pr in the [documentation repo](https://github.com/Volumetrics-io/documentation) that updates the manual docs to match the breaking change
    - link the pr of the documentation repo here: *#pr*
    - that pr must be approved by `@lobau`
  - **SAMPLES/INDEX.HTML**: This includes any changes (html tags or otherwise) that must be done to our landing page submodule as an effect of this pr's updates
    - make a pr in the [mrjs landing page repo](https://github.com/Volumetrics-io/mrjs-landing) that updates the landing page to match the breaking change
    - link the pr of the landing page repo here: *#pr*
    - that pr must be approved by `@hanbollar`

### CODE REVIEW

**Comment by hanbollar** [comment]
so far - have some scrolling working by actual key input presses and text update

to fix for vertical happiness:
- [ ] text deletion struggles with the update for the change in visual scroll
- [ ] cursor movement works until it doesnt
- [ ] the special case where startLineIndex and endLineIndex for textObj are the same

in a future pr:
- horizontal scrolling and word wrap

**Comment by hanbollar** [comment]
> so far on this pr - have some scrolling working by actual key input presses and text update
> 
> to fix for vertical happiness:
> 
> * [ ]  text deletion struggles with the update for the change in visual scroll
> * [ ]  cursor movement works until it doesnt
> * [ ]  the special case where startLineIndex and endLineIndex for textObj are the same
> 
> in a future pr:
> 
> * horizontal scrolling and word wrap

progress:
- [x]  text deletion struggles with the update for the change in visual scroll
- [x]  cursor movement works until it doesnt
- [x]  the special case where startLineIndex and endLineIndex for textObj are the same

outstanding todo:
- [ ] weird case where doing an input key after doing a cursor movement even though no textobj scroll should happen can shift textObj line display by 1, but only on that first cursor direction after a textobj shift --> prob an off by one error somewhere

**Comment by hanbollar** [comment]
> > so far on this pr - have some scrolling working by actual key input presses and text update
> > to fix for vertical happiness:
> > 
> > * [ ]   text deletion struggles with the update for the change in visual scroll
> > * [ ]   cursor movement works until it doesnt
> > * [ ]   the special case where startLineIndex and endLineIndex for textObj are the same
> > 
> > in a future pr:
> > 
> > * horizontal scrolling and word wrap
> 
> progress:
> 
> * [x]   text deletion struggles with the update for the change in visual scroll
> * [x]   cursor movement works until it doesnt
> * [x]   the special case where startLineIndex and endLineIndex for textObj are the same
> 
> outstanding todo:
> 
> * [x]  weird case where doing an input key after doing a cursor movement even though no textobj scroll should happen can shift textObj line display by 1, but only on that first cursor direction after a textobj shift --> prob an off by one error somewhere

outstanding todo:

- [ ] fix offby one maxendline index being too short only on keypress, but fine on scrolling

**Comment by hanbollar** [comment]
> > > so far on this pr - have some scrolling working by actual key input presses and text update
> > > to fix for vertical happiness:
> > > 
> > > * [ ]    text deletion struggles with the update for the change in visual scroll
> > > * [ ]    cursor movement works until it doesnt
> > > * [ ]    the special case where startLineIndex and endLineIndex for textObj are the same
> > > 
> > > in a future pr:
> > > 
> > > * horizontal scrolling and word wrap
> > 
> > 
> > progress:
> > 
> > * [x]    text deletion struggles with the update for the change in visual scroll
> > * [x]    cursor movement works until it doesnt
> > * [x]    the special case where startLineIndex and endLineIndex for textObj are the same
> > 
> > outstanding todo:
> > 
> > * [x]   weird case where doing an input key after doing a cursor movement even though no textobj scroll should happen can shift textObj line display by 1, but only on that first cursor direction after a textobj shift --> prob an off by one error somewhere
> 
> outstanding todo:
> 
> * [ ]  fix offby one maxendline index being too short only on keypress, but fine on scrolling

- [x] fix offby one maxendline index being too short only on keypress, but fine on scrolling

**Comment by hanbollar** [comment]
@michaelthatsit - solved the off-by-1 error, this is now ready for review

[check out my todo list for notes](https://github.com/Volumetrics-io/mrjs/pull/589#issuecomment-2067107043) (doing it written before the review this time instead of answering /oh yea i swear that'll be handled lol/ as part of the review to help with the process a bit)

lmk if any questions ~

**Review by michaelthatsit — APPROVED** [review]
lgtm! and glad you got the lingering cursor issue when switching input fields, forgot to mention it last time.

**Pull request merged**
